### PR TITLE
Add LICENSE file

### PR DESCRIPTION
**Pull request by siwinski**

### CODE REVIEW

**Comment by lisachenko** [comment]
Merged, thanks!

**Comment by siwinski** [comment]
Even though this has been merged, I wanted to provide details about @aik099 's concerns above:

> the years are correct

I just took the year of the first commit in this repo until now

> licensing should happen to specific person (Alexander Lisachenko) or organization (Go! Aspect-Oriented Framework)

I just took the "authors" value from the `composer.json` file

**Comment by lisachenko** [comment]
> I just took the year of the first commit in this repo until now

This year is correct one :)

> licensing should happen to specific person (Alexander Lisachenko) or organization (Go! Aspect-Oriented Framework)
I just took the "authors" value from the composer.json file

I think it will be more correct to license library to all contributors of parser-reflection. However, I don't mind licensing it to me :)

**Comment by loren-osborn** [comment]
👍 

I suppose you could always add `et al` to @lisachenko's name. ;-)

**Pull request merged**
