### PR TITLE
Static ReflectionEngine replaced with injected ReflectionParser

### PR DESCRIPTION
**Pull request by dg**
Hi @lisachenko, thanks for great library!

I created a tool that adds missing PHP 7 typehints to codebase.  It uses Parser Reflection. This tools parses a lot of files (whole project) and checks whether all method's declarations are compatible with their prototype/interfaces. 

It is important that it uses **only** virtual AST-based class reflections and never fallback to existing classes (exception is native classes). ~~So I moved every class_exists() etc. checking to centrail point `ReflectionEngine::isClassEmulated()`.~~ So I replaced static `ReflectionEngine` with injected `ReflectionParser` and moved every class_exists() etc. checking to centrail point `ReflectionParser::getClassReflection()`

PR should be compatible with older behavior.

Now I can replace this rutine with my implementation:

```php
    public function getClassReflection($name)
    {
		if ((class_exists($name, false)
				|| interface_exists($name, false)
				|| trait_exists($name, false)
			) && !(new \ReflectionClass($name))->isUserDefined() // here is a difference
		) {
			return new \ReflectionClass($name);
		}
		return new ParserReflection\ReflectionClass($name, null, $this);
    }
```

~~It is not possible to inherit from ReflectionEngine, because all classes use static ReflectionEngine. One solution is to add something like `EmulatorDeciderInterface` with method `isEmulated` and inject it the same way as locator is injected.~~

~~Other idea is to leave the decision on locator itself. When it can locate class, use this one, when it can't use native one.~~ (Solved by injected `ReflectionParser`).

What do you think?

Idea: renamed ReflectionParser -> ReflectionContext

### CODE REVIEW

**Comment by aik099** [comment]
> This tools parses a lot of files (whole project) and checks whether all method's declarations are compatible with their prototype/interfaces.

In other words you're checking code to avoid `E_STRICT` notice, when running the code?

In project I'm creating using this library (the static code analysis tool: https://github.com/console-helpers/code-insight) I'm also planning to create such feature: https://github.com/console-helpers/code-insight/issues/8. Can you please share your code that performs that check?

**Comment by dg** [comment]
Related to #16

**Comment by dg** [comment]
@aik099 Yes. I will release it in few days.

**Comment by aik099** [comment]
Maybe you can post link to GitHub project so that I can watch to get notification about release?

**Comment by dg** [comment]
Probably it will be named `updater` and located here https://github.com/nette

**Comment by lisachenko** [comment]
Hi, @dg and @aik099! Thank you for the issue reporting and discussion!

I have several thoughts about current implementation: I'm trying to use AST information if possible, but if a class is already loaded, then in many places engine will return native implementation of `ReflectionClass` instead of AST-based to improve the performance. For me it's ok, but for some cases this can be improved, like in your example.

There is a request #2 to always return AST-based classes even for internal and loaded classes. This will require to add extra check in each reflection method `if ($this->isInitialized) { return parent::func(...$args); }`.

What if we put this logic into the static method `ReflectionEngine::isLoaded(string $fullClassName) : bool`?

Then in your code you can use it with the `ReflectionClass::isUserDefined()` method to perform extra logic.

**Comment by dg** [comment]
For my use case is important, that even if class is loaded or not, it will return reflection that is based on parsed file, not in-memory-loaded class. 

So I can create tool that itself uses library ie. Nette\Utils in version 3.0.1 and is able to load in virtual storage project that uses the same named classes from Nette\Utils but in a different version.

Therefore word `isLoaded` sounds like something that will not help me.

**Comment by dg** [comment]
The ideal solution is to replace static ReflectionEngine with object and pass it between other object, so you can create more than one "context" for parsed classes.

I know that there must exist fallback for standard usage like `$rc = new Go\ParserReflection\ReflectionClass($name)`, when default static context will be used.

**Comment by lisachenko** [comment]
@dg, if you want to always use AST version, then you could use `ReflectionFile` to analyze any valid PHP file and extract a class from it, or even parse source code from the string and pass it as second argument to the `ReflectionFile`, it's also possible.

```php
$ast = ReflectionEngine::parseFile('virtual://any-file', '<?php echo "Yes";');
$file = new ReflectionFile('virtual://any-file', $ast);
```

Is it suitable for you? I use this technique inside `goaop/framework` to analyze a content from the string.

**Comment by dg** [comment]
When I extract class from parsed file and call for example `getMethods()`, it will use "loaded" class parent instead of parent I want to use, right?

**Comment by lisachenko** [comment]
It depends on information about loaded files and classes.

When you ask for `getMethods()`, engine checks all parents and asks for methods. If concrete class is already loaded, then native reflection will be used, otherwise a request to the locator will be performed to return a file name for AST analysis.

**Comment by dg** [comment]
As I said, I never want to use loaded class, because it can be a different version of class than I want to use.

**Comment by dg** [comment]
I'll try to prepare more complex PR.

**Comment by dg** [comment]
@lisachenko I tried to create non-static replacement for static ReflectionEngine (it should be 100% compatible).

Because non-static class is injected where needed, I can replace it with own implementation and simply adjust Parser Reflection for my needs.

**Comment by peter279k** [comment]
It looks like some files are conflict in this PR.

I think it should be fixed firstly.

**Comment by lisachenko** [comment]
New year is a good time to clean all old issues and PR ) Closing this one

**Pull request closed without merging**
