### PR TITLE
[Feature] Add support for UnaryMinus and UnaryPlus expressions

### LINKED ISSUE #140: ReflectionException "Could not find handler (..) resolveExprUnaryMinus method" for parameters like $foo-
On latest `master`, when parsing a class method that has a signature like this:

```
public function bar($foo = -1)
```

An exception is thrown when processing the node for `$foo`:

```
Go\ParserReflection\ReflectionException : Could not find handler for the Go\ParserReflection\Resolver\NodeExpressionResolver::resolveExprUnaryMinus method
 \src\Resolver\NodeExpressionResolver.php:171
 \src\Resolver\NodeExpressionResolver.php:150
 \src\ReflectionParameter.php:104
```

The node is of type `PhpParser\Node\Expr\UnaryMinus`

### PR DESCRIPTION
**Pull request by marcovtwout**
Fixes https://github.com/goaop/parser-reflection/issues/140

### CODE REVIEW

**Comment by lisachenko** [comment]
Hello, nice PR! Could you please also add a test somewhere for this, so it will be tested as well?

**Comment by marcovtwout** [comment]
@lisachenko Since there are no tests yet for the other features and this is still for the dev-version, perhaps merge this and create a seperate issue for adding tests?

**Comment by A-jay98** [comment]
@lisachenko Could you give an update regarding this issue? It would be great if you could merge this so that the current version of the library becomes useable again.

**Review by lisachenko — APPROVED** [review]

**Comment by lisachenko** [comment]
thx @marcovtwout 👍

**Pull request merged**
