### PR TITLE
Fixed getParentClass with preloaded Classes

### PR DESCRIPTION
**Pull request by Bob4ever**
See Issue #74

### CODE REVIEW

**Comment by loren-osborn** [comment]
As I've mentioned before, I'm just a contributing user, so my opinions are just that: my opinions. While I created the`ReflectionClass::createReflectionForClass()` method, @lisachenko (and @aik099) will have their own ideas on how they want this project to grow. I added the`ReflectionClass::createReflectionForClass()` method as a temporary addition, and hoped to remove it in the next few PRs when the pass through @lisachenko proposed in #17 were implemented. I still think this is the preferred solution. Does anyone else care to weigh in?

**Comment by aik099** [comment]
Would this change also fix #16 ?

**Comment by Bob4ever** [comment]
@aik099 I think so. I didn't tested it but your issue seems to be the same.

**Comment by aik099** [comment]
I think, that you should add tests to confirm, that correct class is used in all places, where returned object list contains mixed own/parent class properties/methods.

**Comment by loren-osborn** [comment]
@aik099, would you want me to implement the pass through instead as an alternative? I think that is what @lisachenko said he preferred, and would a first step toward switching to a factory As discussed in #2.

**Comment by aik099** [comment]
To keep PR focused just add tests for changes you've made and see if `getMethods` and `getProperties` methods would return proper (not built-in) reflection method/property instances for parent classes.

> would you want me to implement the pass through instead as an alternative?

Not sure that this PR is about that. If you'd like you can do that as well, but as separate PR. Honestly I'm not sure if factory idea from #2 is worth the effort spent on implementing it compared to how often people would use it.

**Comment by loren-osborn** [comment]
I agree that it would be a separate PR, as would the factory, but a PR to merge **INSTEAD** of this one. The ParserReflection factory serves me very well when I used it with AspectMock previously.

**Comment by aik099** [comment]
I prefer granular approach if time allows, where we make small (granular) changes and next changes can replace previous ones if needed.

Please do this and then in separate PR factory can be introduced:

> To keep PR focused just add tests for changes you've made and see if getMethods and getProperties methods would return proper (not built-in) reflection method/property instances for parent classes.

**Comment by loren-osborn** [comment]
@aik099, after thinking more about this I've decided to break the factory feature changes into 3 PRs:

- One to add the pass through.
- Another to make ReflectionEngine's methods instance methods, and instantiate it.
- A third to implement the actual factory.

I'm still pondering a new project I'm contemplating adding as a dependency to the factory change to better deal with shared objects, but would appreciate you reviewing it when it's ready.

--------

With respect to **THIS** PR, my only concern is that it adds complexity to what was intended to be a temporary, throw-away method, mostly added to satisfy Scrutinizer.

**Comment by aik099** [comment]
Do as you see fit then.

**Comment by loren-osborn** [comment]
Just wanted to leave a progress report. This feature, with accompanying tests is almost complete. From my last commit:

> All tests pass again: added passthrough for Functions.
>
> Need to:
>   * Add ReflectionExtension code to emit proper classes.
>   * Refactor

**Comment by loren-osborn** [comment]
I'm sure I seem like a royal flake by now. My 6 year old MacBook Pro died, and as I currently have no income, I'm hobbling by on my 13 year old HP that won't run anything newer than Windows XP. (I may switch it over to Linux soon, but right now I want to keep it **usable**. 

That said, I finally have a fully working implementation of the `ParserReflection` pas through that @lisachenko in #17.  I have a whole lot of refactoring I'd like to do, but with my current situation I'm working at a bit of a snails pace right now. 

While there is a good deal of refactoring I want to do to the main codebase once I've confirmed code coverage, but that should definitely go in a separate PR. The refactoring I want to do still in my pass through branch includes moving several of my utility test methods out of the test suite classes so they can be adequately tested. I haven't looked at much of this in most of a month, so I'm a little rusty, but I can't think of any other glaring issues.

I'm certainly open to any suggestions, but a new PR would be the right place for that. Anyone have a opinion if I should open a PR now, even if it's a bit unpolished, or wait until I think it will stand up better to scrutiny?

**Comment by aik099** [comment]
You can open a new PR with `[WIP]` prefix in title to indicate that you want this to be reviewed, but it's not final version that can be merged.

**Comment by lisachenko** [comment]
I'm going to close this in favor of #82

**Pull request closed without merging**
